#!/bin/bash

echo "Simple Addition Calculator"
read -p "Enter first number: " num1
read -p "Enter second number: " num2
read -p "Enter third number: " num3
read -p "Enter fourth number:: " num4
# Perform addition

result=$((num1 + num2 + num3 + num4 ))
echo "Result: $result"

#This is the main example1
# This is the merge example

#This is the rebase example
#This is the main example2
